spring:
  application:
    name: user-admin
  cloud:
    stream:
      bindings:
        publishMessage-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}config.message
        publishDirectoryUpdate-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}directory.update
      output-bindings: publishMessage-out-0;publishDirectoryUpdate-out-0

powsybl-ws:
  database:
    name: useradmin

useradmin:
  cron:
    announcement-check: 0 */1 * * * *
    announcement-clean: 0 0 2 * * ?
  defaultMaxAllowedCases: 20   # Default allowed cases for a user
  defaultMaxAllowedBuilds: 20  # Default allowed builds for a user
  casesAlertThreshold: 90      # Default usage threshold (percentage) when user gets a warning when uploading cases
