spring:
  application:
    name: user-admin
  cloud:
    stream:
      bindings:
        publishMessage-out-0:
          destination: ${powsybl-ws.rabbitmq.destination.prefix:}config.message
      output-bindings: publishMessage-out-0

powsybl-ws:
  database:
    name: useradmin

useradmin:
  admins:
#    - admin1
#    - admin2
#  defaultMaxAllowedCases: 20   # Default allowed cases for a user (set here for testing purposes)
#  defaultMaxAllowedBuilds: 10  # Default allowed builds for a user (set here for testing purposes)
